# Development environment configuration
spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/user_auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    # driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/labormanagement?currentSchema=auth}
    driver-class-name: org.postgresql.Driver
    # username: root
    # password: root
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.MySQLDialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: auth


logging:
  level:
    "[com.example.userauth]": DEBUG
    "[com.shared.entityaudit]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
  file:
    name: logs/dev.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] [%X{sessionToken}] [%X{X-Request-ID}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] [%X{sessionToken}] [%X{X-Request-ID}] - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,env,metrics,loggers

# Audit Utility Configuration
shared-lib:
  entity-audit:
    enabled: true
  audit:
    enabled: true  # Set to true to enable audit logging
    table-name: audit_event
    hashing-algorithm: SHA-256
    initial-hash-value: 0000000000000000000000000000000000000000000000000000000000000000
  # SFTP Utility Configuration
  sftp:
    enabled: false  # Set to true to enable SFTP operations
    host: localhost
    port: 22
    username: user
    password: password
    remote-directory: /incoming
    local-directory: /tmp/sftp
    known-hosts-file: ~/.ssh/known_hosts
    strict-host-key-checking: true
  filters:
    enabled: true 
server:
  port: 8080

auth:
  internal:
    api-key: ${INTERNAL_API_KEY:4f0d3ac5a91b7fe246d3851c09a2f718f6c8d42704e3b89a1f2d6c7b81e4f0a3}
    api-key-header: X-Internal-Api-Key
