# Development environment configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


logging:
  level:
    "[com.example.userauth]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
  file:
    name: logs/dev.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] [%X{sessionToken}] [%X{X-Request-ID}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] [%X{sessionToken}] [%X{X-Request-ID}] - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,env,metrics,loggers

# Audit Utility Configuration
shared-lib:
  audit:
    enabled: true  # Set to true to enable audit logging
    table-name: audit_event
    hashing-algorithm: SHA-256
    initial-hash-value: 0000000000000000000000000000000000000000000000000000000000000000
  # SFTP Utility Configuration
  sftp:
    enabled: false  # Set to true to enable SFTP operations
    host: localhost
    port: 22
    username: user
    password: password
    remote-directory: /incoming
    local-directory: /tmp/sftp
    known-hosts-file: ~/.ssh/known_hosts
    strict-host-key-checking: true
  filters:
    enabled: true 
server:
  port: 8080